// <auto-generated />
using System;
using ConsoleApp_MP2_L3;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ConsoleApp_MP2_L3.Migrations
{
    [DbContext(typeof(ITAsset3Context))]
    [Migration("20220130182827_Init2")]
    partial class Init2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ConsoleApp_MP2_L3.ITAsset3", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Office")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ITAssets3");

                    b.HasDiscriminator<string>("Discriminator").HasValue("ITAsset3");
                });

            modelBuilder.Entity("ConsoleApp_MP2_L3.Computer", b =>
                {
                    b.HasBaseType("ConsoleApp_MP2_L3.ITAsset3");

                    b.HasDiscriminator().HasValue("Computer");
                });

            modelBuilder.Entity("ConsoleApp_MP2_L3.Phone", b =>
                {
                    b.HasBaseType("ConsoleApp_MP2_L3.ITAsset3");

                    b.HasDiscriminator().HasValue("Phone");
                });
#pragma warning restore 612, 618
        }
    }
}
